export const Quuesstion = [
    {
        id: 1,
        queNo: 'Q1',
        question: 'x2-2x+1 is a polynomial in:?',
        optionOne: 'One Variable',
        optionTwo: 'Two Variables',
        optionThree: 'Three variable',
        optionFour: 'None of the above',
    },
    {
        id: 2,
        queNo: 'Q2',
        question: 'Which of the following angles is acute?',
        optionOne: '90°',
        optionTwo: '45°',
        optionThree: '180°',
        optionFour: '270°',
    },
    {
        id: 3,
        queNo: 'Q3',
        question: 'What is the area of an equilateral triangle with side length 12 cm using Heron’s formula?',
        optionOne: '36√3 sq. cm',
        optionTwo: '72 sq. cm',
        optionThree: '144 sq. cm',
        optionFour: ' 216 sq. cm',
    },
    {
        id: 4,
        queNo: 'Q4',
        question: 'The coefficient of x2 in 3x3+2x2-x+1 is?',
        optionOne: '1',
        optionTwo: '2',
        optionThree: '3',
        optionFour: '-1',
    },
    {
        id: 5,
        queNo: 'Q5',
        question: ' Which of the following pairs of angles are supplementary?',
        optionOne: '30° and 150°',
        optionTwo: '45° and 45°',
        optionThree: '60° and 30°',
        optionFour: '90° and 90°',
    },
    {
        id: 6,
        queNo: 'Q6',
        question: 'The degree of 4x3-12x2+3x+9 is?',
        optionOne: '0',
        optionTwo: '1',
        optionThree: '2',
        optionFour: '3',
    },
    {
        id: 7,
        queNo: 'Q7',
        question: 'Which property states that a + b = b + a for any two real numbers a and b?',
        optionOne: 'Commutative property of addition',
        optionTwo: 'Associative property of addition',
        optionThree: 'Distributive property',
        optionFour: ' Identity property of addition',
    },
    {
        id: 8,
        queNo: 'Q8',
        question: 'How many angles does a triangle have?',
        optionOne: '1',
        optionTwo: '3',
        optionThree: '2',
        optionFour: '4',
    },
    {
        id: 9,
        queNo: 'Q9',
        question: 'The zero of the polynomial p(x) = -5x+5 is?',
        optionOne: '0',
        optionTwo: '-5',
        optionThree: '-1',
        optionFour: '1',
    },
    {
        id: 10,
        queNo: 'Q10',
        question: ' Which of the following pairs of angles are supplementary?',
        optionOne: '30° and 150°',
        optionTwo: '45° and 45°',
        optionThree: '60° and 30°',
        optionFour: '90° and 90°',
    },
    {
        id: 11,
        queNo: 'Q11',
        question: 'Heron’s formula is applicable for which type of triangles?',
        optionOne: 'Equilateral',
        optionTwo: 'Iosceles',
        optionThree: 'Scalene',
        optionFour: 'Right-angled',
    },
    {
        id: 12,
        queNo: 'Q12',
        question: 'Which property states that a × (b × c) = (a × b) × c?',
        optionOne: 'Commutative property of multiplication',
        optionTwo: 'Associative property of multiplication',
        optionThree: 'Distributive property',
        optionFour: ' Identity property of multiplication',
    },
    {
        id: 13,
        queNo: 'Q13',
        question: 'A binomial of degree 20 in the following is?',
        optionOne: '20x + 1',
        optionTwo: ' x/20 + 1',
        optionThree: 'x20 +1',
        optionFour: 'x2+20',
    },
    {
        id: 14,
        queNo: 'Q14',
        question: '. What is the value of 0/5?',
        optionOne: '0',
        optionTwo: '1',
        optionThree: '5',
        optionFour: 'None of the above',
    },
    {
        id: 15,
        queNo: 'Q15',
        question: 'A point that lies on a line is called?',
        optionOne: 'Collinear',
        optionTwo: 'Coplanar',
        optionThree: 'Concurrent',
        optionFour: 'None of the above',
    },
];